/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


DROP TABLE IF EXISTS `admin_old`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `admin_old`
(
    `admin` varchar(128) NOT NULL,
    PRIMARY KEY (`admin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `admin_old`
--

LOCK
TABLES `admin_old` WRITE;
ALTER TABLE `admin_old` DISABLE KEYS */;
INSERT INTO `admin_old`
VALUES ('hecheng');
ALTER TABLE `admin_old` ENABLE KEYS */;
UNLOCK
TABLES;
 SET
TIME_ZONE=@OLD_TIME_ZONE */;

SET
SQL_MODE=@OLD_SQL_MODE */;
 SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
SET
CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
SET
CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
 SET
COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
 SET
SQL_NOTES=@OLD_SQL_NOTES */;


